# Pipeline for additional processing of ASV FASTA files through HoneyPis
#
# Example call: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --conda-prefix ${CONDA_PREFIX}/pipeline --cores 1 -rpn
# Example call with conda-prefix-path: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --conda-prefix ${CONDA_PREFIX}/pipeline --cores $CORES -rpn

##############################
# MODULES
import os, re
import glob
import pandas as pd


# importing specific scripts for parsing etc.
# from scripts.utils import find_fast5, assembler_pairs


##############################
# CONFIG
# can be overwritten by using --configfile <path to config> when calling snakemake
# configfile: "config/config.yaml"

include:
    "rules/init.smk"


##############################
# Paths
SRC_DIR = srcdir("../scripts")
ENV_DIR = srcdir("../envs")


##############################
# default executable for snakemake
# shell.executable("bash")


##############################
# TARGETS & RULES

# List of (main) targets to be created
TARGETS = []

# RDP CLASSIFIER
if "rdp" in STEPS:
    include:
        "rules/rdp_classifier.smk"
    TARGETS += [
        "status/rdp_classifier.done"
    ]

# BLAST
if "blast" in STEPS:
    include:
        "rules/blast.smk"
    TARGETS += [
        "status/blast.done"
    ]


# No targets
if len(TARGETS) == 0:
    raise Exception('You are not serious. Nothing to be done? Really?')

rule all:
    input:
        TARGETS
